CREATE TABLE IF NOT EXISTS `player_horses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `stable` VARCHAR(50) NOT NULL DEFAULT 'valentine',
  `citizenid` VARCHAR(50) NOT NULL,
  `horseid` VARCHAR(6) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `horse` VARCHAR(100) NOT NULL,
  `gender` VARCHAR(10) NOT NULL DEFAULT 'male',
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  `born` INT(11) NOT NULL DEFAULT 0,
  `components` LONGTEXT DEFAULT NULL,
  `coat` LONGTEXT DEFAULT NULL,
  `horsexp` INT(11) NOT NULL DEFAULT 0,
  `dirt` INT(11) NOT NULL DEFAULT 0,
  `age_seconds` INT(11) NOT NULL DEFAULT 0,
  `pregnant_until` INT(11) DEFAULT NULL,
  `last_bred` INT(11) DEFAULT NULL,
  `stored_weapon` VARCHAR(100) DEFAULT NULL,
  `stored_weapon_name` VARCHAR(100) DEFAULT NULL,
  `stored_weapon_data` LONGTEXT DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_citizenid` (`citizenid`),
  KEY `idx_horseid` (`horseid`),
  KEY `idx_active` (`citizenid`, `active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
