
    -- general
    hay             = { name = 'hay',              label = 'Hay',              weight = 300,  type = 'item',  image = 'hay.png',              unique = false,  useable = true,  shouldClose = true,  description = 'Feed for horses, used in breeding',         category = 'general' },
    horse_brush     = { name = 'horse_brush',      label = 'Horse Brush',      weight = 250,  type = 'item',  image = 'horse_brush.png',      unique = false,  useable = true,  shouldClose = true,  description = 'Brush for grooming horses',                 category = 'general' },
    horse_holster   = { name = 'horse_holster',    label = 'Horse Holster',    weight = 800,  type = 'item',  image = 'horse_holster.png',    unique = false,  useable = true,  shouldClose = true,  description = 'Holster for storing long arms on a horse',  category = 'general' },
    horse_lantern   = { name = 'horse_lantern',    label = 'Horse Lantern',    weight = 500,  type = 'item',  image = 'horse_lantern.png',    unique = false,  useable = true,  shouldClose = true,  description = 'Lantern that mounts on a horse',            category = 'general' },
    horse_reviver   = { name = 'horse_reviver',    label = 'Horse Reviver',    weight = 400,  type = 'item',  image = 'horse_reviver.png',    unique = false,  useable = true,  shouldClose = true,  description = 'Revives a dead horse',                      category = 'general' },
    horse_stimulant = { name = 'horse_stimulant',  label = 'Horse Stimulant',  weight = 200,  type = 'item',  image = 'horse_stimulant.png',  unique = false,  useable = true,  shouldClose = true,  description = 'Restores horse health and stamina',         category = 'general' },
    horseapple      = { name = 'horseapple',       label = 'Apple',            weight = 100,  type = 'item',  image = 'horseapple.png',       unique = false,  useable = true,  shouldClose = true,  description = 'Feed for horses',                           category = 'general' },
    horsecarrot     = { name = 'horsecarrot',      label = 'Carrot',           weight = 100,  type = 'item',  image = 'horsecarrot.png',      unique = false,  useable = true,  shouldClose = true,  description = 'Feed for horses',                           category = 'general' },
